version: "3.8"

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db

  backend:
    container_name: backend
    build:
      context: ./app
    command: bash -c "alembic upgrade head && uvicorn app:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db

  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #   volumes:
  #     - .:/frontend
  #   ports:
  #     - 8000:8000
  #   restart: always
  #   depends_on:
  #     - db
